---
name: Checks

on: [push]

jobs:
  test-lint:
    name : Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and run containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: Show container status
        run: |
          docker-compose ps

      - name: Ping db from app container
        run: |
          docker-compose exec app ping db

      - name: Check PostgreSQL server status
        run: |
          docker-compose exec db sh -c "netstat -an | grep 5432"

      - name: Check PostgreSQL server configuration
        run: |
          docker-compose exec db sh -c "cat /var/lib/postgresql/data/pg_hba.conf"
          docker-compose exec db sh -c "cat /var/lib/postgresql/data/postgresql.conf"

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"